// Configuration des icônes Font Awesome
import { library } from '@fortawesome/fontawesome-svg-core';
import {
    // Icônes de navigation et UI
    faHome,
    faSearch,
    faMusic,
    faUsers,
    faCalendarAlt,
    faTh,
    faBars,
    faTimes,
    faArrowLeft,
    faArrowRight,
    faChevronLeft,
    faChevronRight,
    faChevronUp,
    faChevronDown,
    faEllipsisV,
    faEllipsisH,

    // Icônes d'authentification et utilisateur
    faUser,
    faUserCircle,
    faUserPlus,
    faSignInAlt,
    faSignOutAlt,
    faEdit,
    faCog,
    faKey,
    faLock,
    faUnlock,

    // Icônes de contenu musical
    faPlay,
    faPause,
    faStop,
    faForward,
    faBackward,
    faVolumeUp,
    faVolumeDown,
    faVolumeMute,
    faVolumeOff,
    faHeadphones,
    faCompactDisc,
    faMicrophone,

    // Icônes d'interaction
    faHeart,
    faShare,
    faDownload,
    faUpload,
    faShoppingCart,
    faShoppingBag,
    faPlus,
    faMinus,
    faTrash,
    faEye,
    faEyeSlash,
    faThumbsUp,
    faThumbsDown,
    faStar,

    // Icônes d'information
    faInfo,
    faInfoCircle,
    faExclamation,
    faExclamationTriangle,
    faExclamationCircle,
    faQuestion,
    faQuestionCircle,
    faCheck,
    faCheckCircle,
    faTimesCircle,

    // Icônes de statut et notification
    faBell,
    faBellSlash,
    faFlag,
    faShield,
    faShieldAlt,
    faCertificate,
    faAward,
    faTrophy,

    // Icônes de temps et date
    faClock,
    faCalendar,
    faHistory,
    faStopwatch,
    faHourglass,

    // Icônes de localisation et événements
    faMapMarker,
    faMapMarkerAlt,
    faMapPin,
    faLocationArrow,
    faGlobe,
    faTicketAlt,

    // Icônes de fichiers et médias
    faFile,
    faFileAudio,
    faFileImage,
    faFileVideo,
    faFilePdf,
    faFolder,
    faFolderOpen,
    faImage,
    faImages,
    faVideo,
    faCamera,

    // Icônes de commerce et finance
    faEuroSign,
    faDollarSign,
    faCreditCard,
    faMoneyBill,
    faWallet,
    faCoins,
    faReceipt,

    // Icônes de communication et social
    faEnvelope,
    faPhone,
    faComment,
    faComments,

    // Icônes de paramètres et outils
    faWrench,
    faHammer,
    faTools,
    faSliders,
    faSlidersH,
    faFilter,
    faSort,
    faSortUp,
    faSortDown,

    // Icônes de connexion et réseau
    faWifi,
    faSignal,
    faCloud,
    faCloudUpload,
    faCloudDownload,
    faLink,
    faUnlink,

    // Icônes de performance et analytics
    faChartBar,
    faChartLine,
    faChartPie,
    faTachometer,
    faTachometerAlt,

    // Icônes de tag et catégorie
    faTag,
    faTags,
    faBookmark,

    // Icônes d'action et mouvement
    faRefresh,
    faSync,
    faSyncAlt,
    faRedo,
    faUndo,
    faCopy,
    faPaste,
    faCut,
    faSave,

    // Icônes de layout et affichage
    faList,
    faListUl,
    faListOl,
    faTable,
    faColumns,
    faGrip,
    faGripHorizontal,
    faGripVertical,

    // Icônes spécialisées
    faCopyright,
    faGavel,
    faBalanceScale
} from '@fortawesome/free-solid-svg-icons';

import {
    faHeart as faHeartRegular,
    faBookmark as faBookmarkRegular,
    faUser as faUserRegular,
    faEnvelope as faEnvelopeRegular,
    faComments as faCommentsRegular,
    faThumbsUp as faThumbsUpRegular,
    faEye as faEyeRegular,
    faClock as faClockRegular,
    faCalendar as faCalendarRegular,
    faPlayCircle as faPlayCircleRegular,
    faPauseCircle as faPauseCircleRegular,
    faStopCircle as faStopCircleRegular,
    faFile as faFileRegular,
    faFolder as faFolderRegular,
    faImage as faImageRegular,
    faStar as faStarRegular,
    faFlag as faFlagRegular,
    faBell as faBellRegular,
    faCheckCircle as faCheckCircleRegular,
    faTimesCircle as faTimesCircleRegular,
    faQuestionCircle as faQuestionCircleRegular
} from '@fortawesome/free-regular-svg-icons';

import {
    faFacebook,
    faTwitter,
    faInstagram,
    faYoutube,
    faSpotify,
    faSoundcloud,
    faApple,
    faGoogle,
    faLinkedin,
    faWhatsapp,
    faTelegram,
    faDiscord,
    faTiktok,
    faSnapchat
} from '@fortawesome/free-brands-svg-icons';

// Ajouter toutes les icônes à la bibliothèque
library.add(
    // Icônes solid
    faHome,
    faSearch,
    faMusic,
    faUsers,
    faCalendarAlt,
    faTh,
    faBars,
    faTimes,
    faArrowLeft,
    faArrowRight,
    faChevronLeft,
    faChevronRight,
    faChevronUp,
    faChevronDown,
    faEllipsisV,
    faEllipsisH,
    faUser,
    faUserCircle,
    faUserPlus,
    faSignInAlt,
    faSignOutAlt,
    faEdit,
    faCog,
    faKey,
    faLock,
    faUnlock,
    faPlay,
    faPause,
    faStop,
    faForward,
    faBackward,
    faVolumeUp,
    faVolumeDown,
    faVolumeMute,
    faVolumeOff,
    faHeadphones,
    faCompactDisc,
    faMicrophone,
    faHeart,
    faShare,
    faDownload,
    faUpload,
    faShoppingCart,
    faShoppingBag,
    faPlus,
    faMinus,
    faTrash,
    faEye,
    faEyeSlash,
    faThumbsUp,
    faThumbsDown,
    faStar,
    faInfo,
    faInfoCircle,
    faExclamation,
    faExclamationTriangle,
    faExclamationCircle,
    faQuestion,
    faQuestionCircle,
    faCheck,
    faCheckCircle,
    faTimesCircle,
    faBell,
    faBellSlash,
    faFlag,
    faShield,
    faShieldAlt,
    faCertificate,
    faAward,
    faTrophy,
    faClock,
    faCalendar,
    faHistory,
    faStopwatch,
    faHourglass,
    faMapMarker,
    faMapMarkerAlt,
    faMapPin,
    faLocationArrow,
    faGlobe,
    faTicketAlt,
    faFile,
    faFileAudio,
    faFileImage,
    faFileVideo,
    faFilePdf,
    faFolder,
    faFolderOpen,
    faImage,
    faImages,
    faVideo,
    faCamera,
    faEuroSign,
    faDollarSign,
    faCreditCard,
    faMoneyBill,
    faWallet,
    faCoins,
    faReceipt,
    faEnvelope,
    faPhone,
    faComment,
    faComments,
    faWrench,
    faHammer,
    faTools,
    faSliders,
    faSlidersH,
    faFilter,
    faSort,
    faSortUp,
    faSortDown,
    faWifi,
    faSignal,
    faCloud,
    faCloudUpload,
    faCloudDownload,
    faLink,
    faUnlink,
    faChartBar,
    faChartLine,
    faChartPie,
    faTachometer,
    faTachometerAlt,
    faTag,
    faTags,
    faBookmark,
    faRefresh,
    faSync,
    faSyncAlt,
    faRedo,
    faUndo,
    faCopy,
    faPaste,
    faCut,
    faSave,
    faList,
    faListUl,
    faListOl,
    faTable,
    faColumns,
    faGrip,
    faGripHorizontal,
    faGripVertical,
    faCopyright,
    faGavel,
    faBalanceScale,

    // Icônes regular
    faHeartRegular,
    faBookmarkRegular,
    faUserRegular,
    faEnvelopeRegular,
    faCommentsRegular,
    faThumbsUpRegular,
    faEyeRegular,
    faClockRegular,
    faCalendarRegular,
    faPlayCircleRegular,
    faPauseCircleRegular,
    faStopCircleRegular,
    faFileRegular,
    faFolderRegular,
    faImageRegular,
    faStarRegular,
    faFlagRegular,
    faBellRegular,
    faCheckCircleRegular,
    faTimesCircleRegular,
    faQuestionCircleRegular,

    // Icônes brands
    faFacebook,
    faTwitter,
    faInstagram,
    faYoutube,
    faSpotify,
    faSoundcloud,
    faApple,
    faGoogle,
    faLinkedin,
    faWhatsapp,
    faTelegram,
    faDiscord,
    faTiktok,
    faSnapchat
);

export default library;